---
- name: Install php-fpm-70
  yum: name={{ item }} state=latest enablerepo=remi,remi-php70
  with_items:
   - php
   - php-devel
   - php-fpm
   - php-mbstring
   - php-pdo
   - php-mcrypt
   - php-mysqlnd
   - php-opcache
   - php-xml

- name: Set php setting
  lineinfile: >-
   dest='/etc/php.ini'
   regexp=';date.timezone ='
   line='date.timezone = Asia/Tokyo'
  lineinfile: >-
   dest='/etc/php.ini'
   regexp='session.gc_maxlifetime ='
   line='session.gc_maxlifetime = 1800'
  lineinfile: >-
   dest='/etc/php.ini'
   regexp='memory_limit ='
   line='memory_limit = 256M'

- name: Set php-fpm setting
  lineinfile: "dest=/etc/php-fpm.d/www.conf
          state=present
          regexp='^user = apache'
          line='user = nginx'"
  lineinfile: "dest=/etc/php-fpm.d/www.conf
          state=present
          regexp='^group = apache'
          line='group = nginx'"

- name: Run php-fpm
  shell: |
   systemctl start php-fpm
   systemctl enable php-fpm

- name: Set permission php session
  shell: |
   chown nginx /var/lib/php/session
   chgrp nginx /var/lib/php/session
