---
- name: Install nginx
  yum: name=nginx

- name: Chkconfig nginx
  command: systemctl enable nginx.service

- name: Copy nginx default configuration
  template: src={{item.src}} dest={{item.dest}}
  with_items:
   - { src: '../templates/laravel-react-redux-blog-boilerplate.conf', dest: '/etc/nginx/conf.d' }
   - { src: '../templates/wp-bmf-tech.conf', dest: '/etc/nginx/conf.d' }
   - { src: '../templates/localdev.conf', dest: '/etc/nginx/conf.d' }

- name: Restart nginx
  command: systemctl restart nginx
